---
name: Test-JSYNC
version: 0.01
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: Test JSYNC data
license: perl
resources:
  license: ~
requires:
  JSYNC: 0
  Test::Differences: 0.47
  Test::Simple: 0.62
  Test::Tester: 0.107
provides:
  Test::JSYNC:
    file: lib/Test/JSYNC.pm
    version: 0.01
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
